### ISSUE TITLE
Build scripts are very similar and could be generalised

### ISSUE THREAD

**Issue by ConnectedSystems** [daniel-partington/CampaspeModel#5]
Differences appear to be very minor. For example, the difference between 00_..._Steady and 00_..._Cascade is two parameter changes and four additional method calls.

Build scripts could be generalised (as a function that accepts parameters) or generated rather than the current form of individual scripts.

**Comment by daniel-partington** [comment]
Agreed, I have removed _00_Steady_ from the repo, as this is no longer needed
