### ISSUE TITLE
KeyError '83003' - bore related?

### ISSUE THREAD

**Issue by ConnectedSystems** [daniel-partington/CampaspeModel#6]
As in title.

I guess ecological bore data is not included in the model build which is the cause of this. It would be nice to show a more specific error message. 

Relevant error message:

```
File [...]\HydroModelBuilder\ModelInterface\flopyInterface\flopyInterface.py", line 528, in getObservation
    sim_head = head[interval][sim_map_dict[obs][0]][sim_map_dict[obs][1]][sim_map_dict[obs][2]]
KeyError: '83003'
```

**Comment by daniel-partington** [comment]
@ConnectedSystems What did you have in mind for the error message as an example? Should be easy to fix. The ecology bores are not included in the build as they are not necessary to model functioning as they are obs bores. Perhaps I can include a check for them in the build though to make sure they are mapping properly if you think that will help? This way, we avoid any key errors later down the track in the model run scripts.

**Comment by ConnectedSystems** [comment]
@daniel-partington While the ecology bores may not be functionally necessary for a model run, the mode run scripts are still expected to return the depth to gw (at least in its current form). Excerpt from `GW_link_Integrated.py` below for context:

```
ecol_depth_to_gw_bores = ['83003', '89586', '82999', '5662', '44828']
    ecol_depth_to_gw = np.recarray((1,), dtype=[(bore, np.float)
                                                for bore in ecol_depth_to_gw_bores])
    # to set
    for ecol_bore in ecol_depth_to_gw_bores:
        # NOTE: This returns the depth to groundwater below the surface in metres
        # ecol_depth_to_gw[ecol_bore] = modflow_model.getObservation(ecol_bore, 0, 'head')[1]
        ecol_depth_to_gw[ecol_bore] = np.random.rand()
    # end for
```

I've commented out the call to getObservation() and replaced with random number for now so I can continue working on integration.

**Comment by daniel-partington** [comment]
@ConnectedSystems, ok I think a model_linking file is needed listing all of the bores required by the ecology and the policy models. This file will be read firstly in the build to check that the requisite bores are indeed mappable to the model domain and to report if not. I will remove the hard-coded lists of bores from both the build and run scripts and instead read from a text file:

    Ecology: '83003', '89586', '82999', '5662', '44828'   
    Policy: '79234', '62589'

Will that adequately address the problem?

**Comment by ConnectedSystems** [comment]
@daniel-partington A model implementation specific config file would be preferable rather than a straight text file - but lets get it working with a text file as you suggest. Removing hard coded elements alone is a step forward 👍

**Comment by daniel-partington** [comment]
@ConnectedSystems I've found why the ecology bores didn't map in the first place. I will put out a fix tomorrow morning which redefines these bores and other changes as mentioned above.

**Comment by daniel-partington** [comment]
The ecology bores are now identified automatically based on nearest shallow bore to relevant stream gauge that also mapped to the mesh. The text file (model_linking.csv) is still in use in and uses ecology stream gauges rather than ecology bores, but writes ecology bores to the text file for later use when running the model to find depth to groundwater at ecology sites.
