### ISSUE TITLE
Add custom script for defining ecology bores based on stream gauges

### ISSUE THREAD

**Issue by daniel-partington** [daniel-partington/CampaspeModel#7]
The ecology bores used in the GW_link_Integrated model were originally determined by a script that looked for the nearest bores to certain stream gauges along the Campaspe River. This was done quite early in the project, and I think it is time to update this and include it as part of the build of the model. Keen to know your thoughts @ConnectedSystems

**Comment by ConnectedSystems** [comment]
If we end up using this for the Murrumbidgee it would be nice to be able to specify the source/target bores in a flexible manner (and not just for ecology). This may be related work to writing a script generator especially to address e.g. issues #5 and #8

**Comment by daniel-partington** [comment]
This has been resolved in the build script rather than a separate custom script. 
[https://github.com/daniel-partington/CampaspeModel/commit/4ea5eed71c6eac56c6ba519b039ae08ad24a6ddb](url)
