### ISSUE TITLE
CustomScripts folder has many references to hard coded paths

### ISSUE THREAD

**Issue by daniel-partington** [daniel-partington/CampaspeModel#8]
All of the scripts within CustomScripts need to be modified to reference a relative path. All files required will sit within some sort of data folder, which will live elsewhere to GitHub but be available through cloudstor. The working of this have begun but it should be completed to ensure portability and from-scratch builds of the model from any machine.

**Comment by ConnectedSystems** [comment]
@daniel-partington I've started on a build generator which aims to simplify the creation of build scripts in a flexible and composable manner. It can be run and generates a test file that will match up with the GW_link_integrated build script, but is not yet complete.

See [this branch](https://github.com/daniel-partington/CampaspeModel/tree/script-generator/build_generator).

**Comment by ConnectedSystems** [comment]
Issue resolved by carefully replacing path string concatenation with use of os.path.join, and the use of a configuration system
