### ISSUE TITLE
Failing to generate spatial projections for farm

### ISSUE THREAD

**Issue by ConnectedSystems** [daniel-partington/CampaspeModel#9]
Message printed out when mapping farm areas to grid:

`Warning 1: Failed to fetch spatial reference on layer farm_v1_prj_model to build transformer, assuming matching coordinate systems.`

**Comment by daniel-partington** [comment]
Is this still a problem @ConnectedSystems ?

**Comment by ConnectedSystems** [comment]
Past ConnectedSystems wasn't diligent and now I've forgotten what context this occurred. I believe it was during the model build process and you'd see that warning being thrown multiple times. It could be the relevant package(s) being overly cautious.

**Comment by ConnectedSystems** [comment]
Issue no longer occurs so I'm marking this as closed.
